name: AndroidBuild
on:
  pull_request:
    branches: [main]  # Ensure this matches our branch name
  push:
    branches: [main]  # Ensure this matches our branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '8'  # Change this if you need a different Java version
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test  # Run unit tests

      #- name: Run Instrumentation Tests
      #  run: ./gradlew connectedAndroidTest  # Run instrumentation tests (requires emulator)

      - name: Run Lint Checks
        run: ./gradlew lint  # Run lint checks

      - name: Run Static Code Analysis
        run: ./gradlew check  # Run static code analysis

      - name: List APK Output Directory
        run: ls app/build/outputs/apk/debug/  # List APK files

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: toDoList.apk
          path: app/build/outputs/apk/debug/app-debug.apk  # Update this line if necessary
